### ISSUE TITLE
High Sierra 10.13.3

### ISSUE THREAD

**Issue by setegonz** [IJaykkk/alfred-selfcontrol-workflow#6]
I followed installation instructions, the workflow only opens selfcontrol app but doesn't start the countdown. Any advice?

**Comment by Ericlee0210** [comment]
Hi setegonz
Could you tell me your workflow version and provide a screenshot to show where it was stuck?  
Is the script not clicking the "Start" button, or it clicked the button and got stuck at the SecurityAgent window.

**Comment by setegonz** [comment]
Workflow v1.1. The script is not clicking the "Start" button, it is only opening the selcontrol app.

**Comment by Ericlee0210** [comment]
Umm, that's weird! Would the slider change when you enter different length of time? If it does get stuck at clicking "Start" button, there should be an error message showing in the notification which located at the upper-right corner. What does it say?

**Comment by setegonz** [comment]
![kapture 2018-03-04 at 10 42 03](https://user-images.githubusercontent.com/11341688/36946311-df3b356c-1f99-11e8-9b7c-58e39d6ce91a.gif)

**Comment by Ericlee0210** [comment]
Okay, I see.
Could you open up the debug tool like this, and run the workflow again? There would be some messages in the box. If you can provide the information, then I would know where is going wrong.
<img width="945" alt="screen shot 2018-03-05 at 1 14 13 am" src="https://user-images.githubusercontent.com/9026895/36948228-b246f20c-2012-11e8-8dcc-89b65e9641cd.png">

**Comment by setegonz** [comment]
[2018-03-04 15:37:13][input.keyword] Processing output of 'action.script' with arg ''
[2018-03-04 15:37:14][ERROR: action.script] /Users/setegonz/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/6BF8B7A6-186F-4E6F-B7DC-30656D535D8C:214:338: execution error: Can’t get application "Usable Keychain Access". (-1728)
[2018-03-04 15:37:14][action.script] Processing output of 'utility.filter' with arg ''
[2018-03-04 15:37:14][action.script] Processing output of 'utility.filter' with arg ''
[2018-03-04 15:37:14][utility.filter] Processing output of 'output.notification' with arg ''

**Comment by Ericlee0210** [comment]
Try to change `get_pass` function in the script like this:
```
on get_pass()
    set pass to do shell script ("/usr/bin/security 2>&1 >/dev/null find-generic-password -gl 'SelfControl' | cut -c 11-99 | sed 's/\"//g'")
    return pass
end get_pass
```

**Comment by setegonz** [comment]
Now it works! Thanks!!!!
